### ISSUE TITLE
Further Developmen, Implementation and Documentation

### ISSUE THREAD

**Issue by trotsiuk** [trotsiuk/r3PG#93]
### Description

There are several suggestions and ideas for the further development of the `r3PG` package. Unfortunately, due to the limited capacity it is rather difficult to implement those suggestions at the current stage.

Suggestions were provided as individual issues. Here I summarise all those suggestions with the links to the individual issues. One can re-open the issue and make the development or implementation.

This page can act sort-of a WiKi summarising the important points and suggestions.

### Suggestions

- [ ] Pruning and irrigation in the management options #15 
- [ ] Automatic ecological sensibility checks #59 
- [ ] `Qa` and `Qb` being site specific vs species specific #67 
- [ ] Self-thinning/mortality #74 

### Important information

There are some further important information (mainly about soil variables) how to retrieve input parameters for the model.

- Soil water availability #51 
- Soil class - Soil texture #77 
- why is e20 2.2 #84
